angular.module('money.views', []).run(['$templateCache', function($templateCache) {
  "use strict";
  $templateCache.put("checklist/checklist-create.view.html",
    "<div class=modal tabindex=-1 role=dialog><div class=modal-dialog><div class=modal-content><form class=formly name=vm.form novalidate ng-submit=vm.save()><div class=modal-header ng-show=title><button type=button class=close ng-click=$hide()>&times;</button><h4 class=modal-title ng-bind-html=title></h4></div><div class=modal-body><formly-form form=vm.form model=vm.data fields=vm.fields></formly-form></div><div class=modal-footer><button type=button class=\"btn btn-default\" ng-click=$hide()>取消</button> <button type=submit class=\"btn btn-primary\">保存</button></div></form></div></div></div>");
  $templateCache.put("checklist/checklist-detail.view.html",
    "<article class=\"article container-fluid\" ng-init=vm.activate()><header><h3>{{::vm.data.title}}</h3><div><time pubdate>{{::vm.data.created | date:'yyyy-MM-dd'}}</time><author class=author>{{::vm.data.author}}</author><span class=author>{{::vm.data.group}}</span></div></header><div ng-bind-html=::vm.data.content></div></article>");
  $templateCache.put("checklist/checklist-list.view.html",
    "<div class=container-fluid><div class=\"toolbarContainer clearfix\" fs-affix><div class=pull-left><form class=\"form-inline searchForm\" novalidate ng-submit=vm.tableParams.reload()><div class=form-group><label for=search_content>关键字</label><input class=form-control id=search_content placeholder=内容关键字 ng-model=vm.options.keywords></div><div class=form-group><label for=search_author>作者</label><select class=form-control name=search_author id=search_author ng-model=vm.options.author ng-options=\"author for author in vm.authors\"><option value=\"\">全部</option></select></div><button type=submit class=\"form-group btn btn-default\">搜索</button></form></div><div class=\"btn-toolbar pull-right\"><a class=\"btn btn-primary btn-group\" ng-click=vm.showDialog()><i class=\"fa fa-plus\"></i> 新增</a></div></div>{{vm.checklist}}<table fs-table-dynamic=\"vm.tableParams with vm.cols\" class=\"table table-condensed table-bordered table-hover table-group\"><colgroup><col><col width=\"100px\"><col width=\"120px\"></colgroup><tr class=fs-table-group ng-repeat-start=\"group in $groups\"><td colspan=3 class=text-left><a href=javascript:; ng-click=\"group.$hideRows = !group.$hideRows\"><span class=fa ng-class=\"{ 'fa-chevron-right': group.$hideRows, 'fa-chevron-down': !group.$hideRows }\"></span> <strong>{{ group.value }}</strong></a></td></tr><tr ng-hide=group.$hideRows ng-repeat=\"row in group.data\" ng-repeat-end><td ng-repeat=\"col in $columns\" ng-switch=col.field ng-class=col.cellClass><input ng-switch-when=selector type=checkbox ng-model=\"checkboxes.items[row.courseid]\"><div ng-switch-when=operation class=operation><button ng-repeat=\"button in col.buttons\" class=\"btn btn-primary btn-xs\" ng-class=button.css ng-click=button.onClick(row)><i class=fa ng-if=button.icon ng-class=button.icon></i>{{button.text}}</button></div><div ng-switch-default><div ng-if=!!col.getValue ng-bind-html=col.getValue(this,row)></div><div ng-if=!!col.render ng-bind-html=col.render(row,this)></div><div ng-if=\"!col.getValue && !col.render\">{{row[col.field]}}</div></div></td></tr></table></div>");
  $templateCache.put("common/insertImage.tpl.html",
    "<div class=modal tabindex=-1 role=dialog aria-hidden=true><div class=modal-dialog><div class=modal-content><div class=modal-header ng-show=title><button type=button class=close aria-label=Close ng-click=$hide()><span aria-hidden=true>&times;</span></button><h4 class=modal-title ng-bind=title></h4></div><div class=modal-body><div fs-tabs><div title=本地上传 fs-pane><div fsf-drop fsf-select=uploadFiles($files) class=drop-box fsf-drag-over-class=dragover fsf-multiple=true fsf-allow-dir=true accept=image/*,application/pdf fsf-pattern=\"'image/*'\">拖放/单击这里上传图片</div><div fsf-no-file-drop>该浏览器不支持文件拖放</div><ul><li ng-repeat=\"f in data.imageFiles\">{{f.name}} {{f.$error}} {{f.$errorParam}}<div class=progress ng-show=\"f.progress >= 0\"><div class=progress-bar role=progressbar aria-valuenow={{f.progress}} aria-valuemin=0 aria-valuemax=100 style=\"width: {{f.progress}}%\" ng-bind=\"f.progress + '%'\"></div></div><img class=\"img-rounded img-responsive\" fsf-src=f></li></ul></div><div title=网络图片 fs-pane><form name=data.imageForm class=form-horizontal><div class=form-group><label for=imageUrl class=\"col-sm-2 control-label\">图片地址</label><div class=col-sm-10><input type=url ng-model=data.imageUrl class=form-control id=imageUrl placeholder=图片地址></div></div></form></div></div></div><div class=modal-footer><button type=button class=\"btn btn-default\" ng-click=submit()>确定</button> <button type=button class=\"btn btn-default\" ng-click=$hide()>取消</button></div></div></div></div>");
  $templateCache.put("common/table/table-checkbox.tpl.html",
    "<input type=checkbox ng-model=vm.checkboxes.checked class=select-all>");
  $templateCache.put("common/table/table.tpl.html",
    "<table fs-table-dynamic=\"tableParams with cols\" class=\"table table-striped table-bordered table-hover\"><tr ng-repeat=\"row in $data\"><td ng-repeat=\"col in $columns\" ng-switch=col.field><input ng-switch-when=selector type=checkbox ng-model=\"checkboxes.items[row.courseid]\"><div ng-switch-when=operation class=operation><button ng-repeat=\"button in col.buttons\" class=\"btn btn-primary btn-xs\" ng-class=button.css ng-click=button.onClick(row)><i class=fa ng-if=button.icon ng-class=button.icon></i>{{button.text}}</button></div><div ng-switch-default><div ng-if=!!col.getValue ng-bind=col.getValue(this,row)></div><div ng-if=!!col.render ng-bind-html=col.render(row,this)></div><div ng-if=\"!col.getValue && !col.render\">{{row[col.field]}}</div></div></td></tr></table>");
  $templateCache.put("formlyBootstrap/checkbox.type.html",
    "<div class=checkbox><label ng-class=\"{'required':to.required}\"><input type=checkbox class=formly-field-checkbox ng-model=model[options.key]> {{to.label}}</label></div>");
  $templateCache.put("formlyBootstrap/input.type.html",
    "<input class=form-control id={{id}} ng-model=model[options.key]>");
  $templateCache.put("formlyBootstrap/label.wrapper.html",
    "<label for={{id}} class=\"control-label {{to.labelSrOnly ? 'sr-only' : ''}}\" ng-if=to.label ng-class=\"{'sr-only':to.labelSrOnly,'required':to.required}\">{{to.label}}</label><formly-transclude></formly-transclude>");
  $templateCache.put("formlyBootstrap/multiCheckbox.type.html",
    "<div class=radio-group><div ng-repeat=\"(key, option) in to.options\" class=checkbox><label><input type=checkbox id=\"{{id + '_'+ $index}}\" ng-model=multiCheckbox.checked[$index] ng-change=multiCheckbox.change()> {{option[to.labelProp || 'name']}}</label></div></div>");
  $templateCache.put("formlyBootstrap/radio.type.html",
    "<div class=radio-group><div class=radio ng-repeat=\"(key, option) in to.options\"><label><input type=radio id=\"{{id + '_'+ $index}}\" tabindex=0 ng-value=\"option[to.valueProp || 'value']\" ng-model=model[options.key]> {{option[to.labelProp || 'name']}}</label></div></div>");
  $templateCache.put("formlyBootstrap/richEditor.type.html",
    "<text-angular id={{id}} ng-model=model[options.key] fs-rich-editor-patch></text-angular>");
  $templateCache.put("formlyBootstrap/select.type.html",
    "<select class=form-control ng-model=model[options.key]></select>");
  $templateCache.put("formlyBootstrap/textarea.type.html",
    "<textarea class=form-control id={{id}} ng-model=model[options.key]></textarea>");
  $templateCache.put("formlyBootstrap/typeahead-multiple.type.html",
    "<fs-typeahead multiple data-ng-model=model[options.key] data-required={{to.required}} data-disabled={{to.disabled}} theme=bootstrap><fs-typeahead-match placeholder={{to.placeholder}}>{{$item[to.labelProp]}}</fs-typeahead-match><fs-typeahead-choices data-repeat={{to.ngOptions}}><div ng-bind-html=\"option[to.labelProp] | highlight: $select.search\"></div></fs-typeahead-choices></fs-typeahead>");
  $templateCache.put("formlyBootstrap/typeahead-single-async.type.html",
    "<fs-typeaheadt data-ng-model=model[options.key] data-required={{to.required}} data-disabled={{to.disabled}} theme=bootstrap><fs-typeaheadt-match placeholder={{to.placeholder}}>{{$select.selected[to.labelProp]}}</fs-typeaheadt-match><fs-typeaheadt-choices data-repeat={{to.ngOptions}} data-refresh=\"to.refresh($select.search, options)\" data-refresh-delay={{to.refreshDelay}}><div ng-bind-html=\"option[to.labelProp] | highlight: $select.search\"></div><div><small>{{option.geometry.location.lat}}, {{option.geometry.location.lng}}</small></div></fs-typeaheadt-choices></fs-typeaheadt>");
  $templateCache.put("formlyBootstrap/typeahead-single.type.html",
    "<fs-typeahead data-ng-model=model[options.key] data-required={{to.required}} data-disabled={{to.disabled}} theme=bootstrap><fs-typeahead-match placeholder={{to.placeholder}} data-allow-clear=false>{{$select.selected[to.labelProp]}}</fs-typeahead-match><fs-typeahead-choices data-repeat={{to.ngOptions}}><div ng-bind-html=\"option[to.labelProp] | highlight: $select.search\"></div></fs-typeahead-choices></fs-typeahead>");
  $templateCache.put("formlyBootstrap/validation-states.wrapper.html",
    "<div class=\"form-group has-feedback\" ng-class=\"{'has-success': fc.$valid && (fc.$touched || validation.show || form.$submitted),'has-error':fc.$invalid && (fc.$touched || validation.show || form.$submitted)}\"><formly-transclude></formly-transclude><span class=\"form-control-feedback fa\" ng-class=\"{'fa-check':fc.$valid && (fc.$touched || validation.show || form.$submitted),'fa-remove':fc.$invalid && (fc.$touched || validation.show || form.$submitted)}\" aria-hidden=true></span><div class=error-messages ng-messages=fc.$error ng-if=\"fc.$invalid && (fc.$touched || validation.show || form.$submitted)\"><div class=some-message ng-message={{::name}} ng-repeat=\"(name,message) in ::options.validation.messages\">{{message(fc.$viewValue,fc.$modelValue,this)}}</div></div></div>");
  $templateCache.put("login/login.view.html",
    "<ion-view view-title=登录 class=loginScreen><ion-content><form id=ml-login ng-submit=vm.doLogin(vm.user) novalidate><div class=introHeading><a class=logo><i class=ion-social-yen></i></a><h1 style=\"color: #fff;text-align: center\"><strong>我的钱</strong></h1></div><button class=submit type=submit><i class=ion-locked></i></button> <i class=\"ion-email inputUserIcon\"></i> <input class=user placeholder=用户名 ng-model=\"vm.user.username\"> <i class=\"ion-key inputPassIcon\"></i> <input type=password class=pass placeholder=密码 ng-model=\"vm.user.password\"><div class=padding><div class=row><div class=col><a ui-sref=forgot-password class=mlLinksBlue>忘记密码?</a></div><div class=col><p class=text-right><a ui-sref=register class=mlLinksBlue>注册账号</a></p></div></div></div></form></ion-content></ion-view>");
  $templateCache.put("wrap/tabs.view.html",
    "<ion-tabs class=\"tabs-icon-top tabs-color-active-positive\"><ion-tab title=Checklist icon-off=ion-ios-pulse icon-on=ion-ios-pulse-strong ui-sref=tabs.checklist><ion-nav-view name=tab-checklist></ion-nav-view></ion-tab><ion-tab title=Chats icon-off=ion-ios-chatboxes-outline icon-on=ion-ios-chatboxes href=#/tab/chats><ion-nav-view name=tab-chats></ion-nav-view></ion-tab><ion-tab title=Account icon-off=ion-ios-gear-outline icon-on=ion-ios-gear href=#/tab/account><ion-nav-view name=tab-account></ion-nav-view></ion-tab></ion-tabs>");
}]);
